#!/bin/bash

$PREFIX/bin/check-updates

if [ $# -eq 0 ]
then
	echo "Empty argument, use --help to see available arguments"
elif [ $1 = "--start" ]
then
	echo "Starting Termux-x11..."
	termux-x11 :0 &>/dev/null & pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 &>/dev/null
	echo ""
	echo -e "Termux-x11 started"
	echo ""
	echo "Starting Box64Droid..."
	$PREFIX/bin/start-box64droid
	pkill -f "app_process / com.termux.x11"
elif [ $1 = "--update" ]
then
	if [ -f ~/ubuntu/opt ]
	then
		cd ~/ubuntu/opt
		sudo wget https://github.com/GabiAle97/Box64Droid/releases/download/mod_box/scripts.tar.gz
		sudo tar -xf scripts.tar.gz
		sudo rm -rf scripts.tar.gz
	else
		cd /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/opt
		wget https://github.com/GabiAle97/Box64Droid/releases/download/mod_box/scripts.tar.gz
		tar -xf scripts.tar.gz
		rm -rf scripts.tar.gz
	fi
elif [ $1 = "--reinstall" ]
then
	echo "Uninstalling Box64Droid..."
	proot-distro remove ubuntu &>/dev/null
	rm $PREFIX/bin/box64droid
	rm $PREFIX/bin/start-box64droid
	cd ~/
	curl -o install https://raw.githubusercontent.com/GabiAle97/Box64Droid/main/scripts/install && chmod +x install && ./install
elif [ $1 = "--uninstall" ]
then
	echo "Uninstalling Box64Droid..."
	proot-distro remove ubuntu &>/dev/null
	rm $PREFIX/bin/box64droid
	rm $PREFIX/bin/start-box64droid
	echo "Done!"
elif [ $1 = "--version" ]
then
        echo "25.08.23"
elif [ $1 = "--help" ]
then
        echo "Box64Droid - preconfigured Ubuntu 22.04 rootfs with Box64, Box86, Wine Proton, DXVK and Adreno GPU drivers for Android"
	echo "Usage: box64droid {argument}"
	echo "Available arguments:"
	echo "--start - start Box64Droid"
	echo "--update - update Box64Droid"
	echo "--uninstall - uninstall Box64Droid (all data in rootfs will be clear)"
	echo "--version - show current version of Box64Droid"
	echo "--help - see available arguments"
else
	echo "Invalid argument, use --help to see available arguments"
fi
